import { prisma } from "@repo/db";
import type { ProjectModel } from "./model";

export abstract class ProjectService {
  // Service:: to get all the projects
  static async getAllProjects(
    userId: string,
    { page = 1, pageSize = 10 }: ProjectModel["getProjectsRequestQuery"],
  ) {
    const skip = (page - 1) * pageSize;

    const projects = await prisma.project.findMany({
      where: {
        userId,
      },
      skip,
      take: pageSize,
      orderBy: {
        createdAt: "desc",
      },
    });

    return projects;
  }

  // Service:: to get one project
  static async getProjectByName(
    userId: string,
    { name }: ProjectModel["getProjectNameParam"],
  ) {
    const project = await prisma.project.findUniqueOrThrow({
      where: {
        name,
        userId,
      },
    });

    return project;
  }

  // Service:: to create project
  static async createProject(
    userId: string,
    body: ProjectModel["createProjectBody"],
  ) {
    const project = await prisma.project.create({
      data: {
        name: body.name,
        description: body.description || "",
        template: body.template,
        userId,
      },
    });

    // 1. Give it a basic package.json so E2B Sandbox can install & run it
    const initialFiles = [];
    if (body.template === "react") {
      initialFiles.push({
        path: "package.json",
        content: JSON.stringify({
          name: "vite-react-fallback",
          version: "0.0.0",
          scripts: { dev: "vite", build: "vite build" },
          dependencies: { react: "^18.2.0", "react-dom": "^18.2.0" },
          devDependencies: { 
            "vite": "^5.2.0",
            "@vitejs/plugin-react": "^4.2.1"
          }
        }, null, 2)
      });
      initialFiles.push({
        path: "index.html",
        content: `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <title>Vite App</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.jsx"></script>\n  </body>\n</html>`
      });
      initialFiles.push({
        path: "src/main.jsx",
        content: `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App.jsx';\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);`
      });
      initialFiles.push({
        path: "src/App.jsx",
        content: `export default function App() {\n  return <div>Welcome to ${project.name}!</div>;\n}`
      });
      initialFiles.push({
        path: "vite.config.js",
        content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n  server: {\n    allowedHosts: true\n  }\n});`
      });
    }

    // Save initial DB snapshots
    for (const file of initialFiles) {
      await prisma.fileSnapshot.create({
        data: {
          projectId: project.id,
          filePath: file.path,
          content: file.content
        }
      });
    }

    try {
      // 2. Create the GitHub Repo dynamically
      const { GithubService } = await import("@server/utils/github");
      const repoData = await GithubService.createRepository(
        userId,
        project.name,
        project.description || "Project generated by Lynx Code"
      );

      if (initialFiles.length > 0) {
        await GithubService.commitFiles(userId, {
          owner: repoData.owner.login,
          repo: repoData.name,
          message: "Initial commit",
          files: initialFiles,
        });
      }

      const updatedProject = await prisma.project.update({
        where: { id: project.id },
        data: {
           githubRepoUrl: repoData.html_url,
           githubRepoOwner: repoData.owner.login,
           githubRepoName: repoData.name,
        },
      });

      return updatedProject;
    } catch (e: any) {
      console.error("Github Provisioning Failed on basic project creation:", e.message);
      return project;
    }
  }

  // Service:: to update the project with different fields
  static async updateProject(
    userId: string,
    params: ProjectModel["updateProjectNameParams"],
    body: ProjectModel["updateProject"],
  ) {
    await prisma.project.update({
      where: {
        id: params.id,
        userId,
      },
      data: {
        name: body.name,
        description: body.description,
        template: body.template,
        updatedAt: new Date(),
      },
    });
  }

  // Service:: to delete a project via project id
  static async deleteProjectById(
    userId: string,
    params: ProjectModel["deleteProjectParams"],
  ) {
    await prisma.project.delete({
      where: {
        id: params.id,
        userId,
      },
    });
  }
}
